services:
  bookstore-api:
    image: saulodias/bookstore:latest #Docker Hub
    container_name: bookstore-api-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://bookstore-db:5432/bookstore
      SPRING_DATASOURCE_USERNAME: my_user
      SPRING_DATASOURCE_PASSWORD: my_secret
    depends_on:
      - bookstore-db
    restart: always

  bookstore-db:
    image: postgres:15-alpine
    container_name: bookstore-db-container
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_secret
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
