server:
  port: 8081
  servlet:
    context-path: "/bookstore-consumer-api"

api:
  bookstore:
    url: "http://localhost:8080/bookstore-api"

spring:
  application:
  name: BookStoreConsumer
  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - openid
              - profile
              - email
            client-id: "61911610387-02vbrps8tfp031j4850ihde8c9rqgdgh.apps.googleusercontent.com"
            client-secret: "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"
            redirect-uri: "http://localhost:8081/bookstore-consumer-api/login/oauth2/code/google"
          github:
            client-id: "Ov23libHD1JBDsxubt8f"
            client-secret: "55f0bd954d0e548f32d31ee105493076a5b8eff5"

springdoc:
  api-docs:
    enabled: false
    path: "/v3/api-docs"
  swagger-ui:
    url: "/api-docs.yaml"

jwt:
  secret: "chave-de-seguranca"

logging:
  level:
    br.com.bookstoreconsumer.adapters.clients: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    root: info



