server:
  port: 8081
  servlet:
    context-path: "/bookstore-consumer-api"

api:
  bookstore:
    url: "http://localhost:8080/bookstore-api"

spring:
  application:
  name: BookStoreConsumer
  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - openid
              - profile
              - email
            client-id: ""
            client-secret: ""
            redirect-uri: ""
          github:
            client-id: ""
            client-secret: ""

springdoc:
  api-docs:
    enabled: false
    path: "/v3/api-docs"
  swagger-ui:
    url: "/api-docs.yaml"

jwt:
  secret: "chave-de-seguranca"

logging:
  level:
    br.com.bookstoreconsumer.adapters.clients: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    root: info



